# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEPKZQeJxo7ARBYNdYw0chvBqm4EMRoa
"""

import streamlit as st

st.set_page_config(page_title="Calculadora Comisión MSI", layout="centered")

st.title("📱 Calculadora de Comisiones")

st.markdown("Ingresa el monto a cobrar y configura las comisiones para ver cuánto recibirías o cuánto deberías cobrar.")

# Entradas
monto = st.number_input("💵 Monto base", min_value=0.0, value=1000.0, step=100.0)
comision_base = st.number_input("🏦 Comisión base (%) sin IVA", min_value=0.0, value=3.5, step=0.01)
usar_msi = st.checkbox("¿Aplicar MSI (Meses Sin Intereses)?")

# Sobretasas MSI (sin IVA)
comisiones_msi = {
    3: 4.19,
    6: 6.99,
    9: 9.69,
    12: 12.51,
    18: 17.99,
    24: 22.99
}

plazo_msi = None
if usar_msi:
    plazo_msi = st.selectbox("Plazo MSI", options=list(comisiones_msi.keys()), index=1)

# Calcular comisiones
if usar_msi and plazo_msi:
    sobretasa = comisiones_msi[plazo_msi]
    comision_sin_iva = comision_base + sobretasa
else:
    comision_sin_iva = comision_base

comision_con_iva = comision_sin_iva * 1.16
comision_decimal = comision_con_iva / 100

# Cálculos
recibido = monto * (1 - comision_decimal)
cobrar = monto / (1 - comision_decimal)

# Resultados
st.subheader("🔍 Resultados")

st.markdown(f"**Comisión sin IVA:** {comision_sin_iva:.2f}%")
st.markdown(f"**Comisión con IVA aplicada:** {comision_con_iva:.2f}%")

# Monto recibido y a cobrar con formato más visual
st.markdown(
    f"""
    <div style="background-color:#d4edda;padding:15px;border-radius:10px;">
        💰 Si cobras <strong>${monto:,.2f}</strong>,<br>
        <span style="font-size:22px;">recibirás aproximadamente <strong>${recibido:,.2f}</strong></span>
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <div style="background-color:#d1ecf1;padding:15px;border-radius:10px;margin-top:10px;">
        🧾 Para recibir <strong>${monto:,.2f}</strong> netos,<br>
        <span style="font-size:22px;">deberías cobrar aproximadamente <strong>${cobrar:,.2f}</strong></span>
    </div>
    """,
    unsafe_allow_html=True
)

# Mensualidades
if usar_msi and plazo_msi:
    mensualidad = monto / plazo_msi
    st.markdown(f"📅 El cliente pagará en {plazo_msi} mensualidades de aproximadamente **${mensualidad:.2f}**.")

# Footer
st.markdown("---")
st.caption("Calculadora optimizada para uso móvil - FINARQ © 2026")
